name: CI-Branch
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
      branches: [ dev, stage ]
    pull_request:
      branches: [ dev, stage ]
# A  workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-model:
        name: Branch Specific Logic
        runs-on: ubuntu-latest        
        env:
          ACTION_SERVER: http://bot.jovensalud.net/actions/ 
          AWS_MODEL_DIRECTORY: 'Models'
          BOT_MODEL_DIRECTORY: './models'
          RUN_TRAINING: 'false'

        steps:
        - uses: actions/checkout@v2   
        - id: files
          uses: jitterbit/get-changed-files@v1

        - name: Echo
          shell: bash
          run: |
            echo Heyyyyy

        # - name: Set up Python 3.7
        #   uses: actions/setup-python@v1
        #   with:
        #     python-version: 3.7
    
        # - name: Install dependencies, set env
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install -r requirements.txt                
                    
        # - name: Rasa Data Validation
        #   working-directory: ${{ github.workspace }}
        #   run: |
        #     rasa data validate --debug 
        

        - name: set_training
          if: |
                contains(  steps.files.outputs.all, 'data/' ) 
                || contains(  steps.files.outputs.all, 'config.yml' ) 
                || contains(  steps.files.outputs.all, 'domain.yml' )
          run: |
                echo "RUN_TRAINING=true"  >> $GITHUB_ENV
                echo "training should run"

        - name: Train model
          if: env.RUN_TRAINING == 'true'
          run: |
              echo "simulate model training"
        
        
        - name: get model list from S3 
          if: env.RUN_TRAINING == 'false'
          run: |
              echo "simulate model listing"
        
        - name: download from s3
          if: env.RUN_TRAINING == 'false'
          run: |
              echo "simulate model download"

        - uses: keithweaver/aws-s3-github-action@master
          with:
            command: ls
            source: s3://jovenslaudbot/Models
            # destination: s3://yourbucket/folder/local_file.txt
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # uses: prewk/s3-cp-action@master
          # env:
          #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #   AWS_REGION: 'us-east-1' # optional: defaults to us-east-1
          #   SOURCE: 's3://jovensaludbot/TEMP/'
          #   DEST: './models'
            
        - name: Run Through Test Stories
          run: |
              echo "simulate model test"
        
        - name: Upload model to S3 
          if: env.RUN_TRAINING == 'true'
          run: |
                echo "simulate model upload to S3"
        #   uses: jakejarvis/s3-sync-action@v0.5.1
        #   env:
        #     SOURCE_DIR: './models'
        #     AWS_REGION: 'us-east-1'
        #     AWS_S3_BUCKET: 'jovensaludbot'
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     DEST_DIR: 'Models'
        
        
        - name: Upload model to rasa - x     
          if: env.RUN_TRAINING == 'true'  && github.ref == 'refs/heads/stage' 
          working-directory: ${{ github.workspace }}
          run: |
                echo "simulate model upload to rasa-x"

  
